"""Add row_count and column_count to datasets

Revision ID: 0655efc3aabe
Revises: abe9b24e148e
Create Date: 2026-07-01 09:56:41.951086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0655efc3aabe'
down_revision: Union[str, Sequence[str], None] = 'abe9b24e148e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('row_count', sa.Integer(), nullable=True))
    op.add_column('datasets', sa.Column('column_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'column_count')
    op.drop_column('datasets', 'row_count')
    # ### end Alembic commands ###
