"""Enhance Batch model for processing lifecycle

Revision ID: 259399123e01
Revises: 608210dc3856
Create Date: 2026-07-04 00:22:55.710381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259399123e01'
down_revision: Union[str, Sequence[str], None] = '608210dc3856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('processing_started_at', sa.DateTime(), nullable=True))
    op.add_column('batches', sa.Column('processing_completed_at', sa.DateTime(), nullable=True))
    op.add_column('batches', sa.Column('health_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'health_score')
    op.drop_column('batches', 'processing_completed_at')
    op.drop_column('batches', 'processing_started_at')
    # ### end Alembic commands ###
