"""Add row_count and column_count to datasets

Revision ID: 507bf45a1dc6
Revises: 0655efc3aabe
Create Date: 2026-07-01 09:57:38.756956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '507bf45a1dc6'
down_revision: Union[str, Sequence[str], None] = '0655efc3aabe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
