"""add missing value drift to drift reports

Revision ID: 8c7fed2b2214
Revises: cb811d2fb1e5
Create Date: 2026-07-15 23:46:46.911476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7fed2b2214'
down_revision: Union[str, Sequence[str], None] = 'cb811d2fb1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drift_reports', sa.Column('missing_value_drift', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drift_reports', 'missing_value_drift')
    # ### end Alembic commands ###
