"""Create drift reports table

Revision ID: 96879028e9a4
Revises: 259399123e01
Create Date: 2026-07-05 23:19:08.785000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96879028e9a4'
down_revision: Union[str, Sequence[str], None] = '259399123e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('psi_results', sa.JSON(), nullable=True),
    sa.Column('ks_results', sa.JSON(), nullable=True),
    sa.Column('chi_square_results', sa.JSON(), nullable=True),
    sa.Column('js_results', sa.JSON(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.create_index(op.f('ix_drift_reports_id'), 'drift_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drift_reports_id'), table_name='drift_reports')
    op.drop_table('drift_reports')
    # ### end Alembic commands ###
